world: 
  name: MazeWorld
  size: 7
model: 
#  name: PlannerModel
#  depth: 8
#  pre_project: false
#  continuous: true
  name: ReflexModel
  depth: 8
  pre_project: false
  continuous: true
trainer: 
  name: ImitationTrainer
